/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as RoomsRouteImport } from './routes/rooms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as ApiDevicesRouteImport } from './routes/api/devices'
import { Route as ApiMockAlertRouteImport } from './routes/api/mock-alert'
import { Route as ApiWeatherRouteImport } from './routes/api/weather'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardHistoryRouteImport } from './routes/dashboard.history'
import { Route as DashboardRecommendationsRouteImport } from './routes/dashboard.recommendations'
import { Route as DashboardRoomsRouteImport } from './routes/dashboard.rooms'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardWeatherRouteImport } from './routes/dashboard.weather'
import { Route as ApiDeviceDataRouteImport } from './routes/api/device.data'
import { Route as ApiDeviceHistoryRouteImport } from './routes/api/device.history'
import { Route as ApiDeviceLatestRouteImport } from './routes/api/device.latest'
import { Route as ApiDevicesIdRouteImport } from './routes/api/devices.$id'
import { Route as ApiDevicesDataRouteImport } from './routes/api/devices.data'
import { Route as ApiPushSubscribeRouteImport } from './routes/api/push.subscribe'
import { Route as ApiPushVapidRouteImport } from './routes/api/push.vapid'
import { Route as ApiUserAlertPreferencesRouteImport } from './routes/api/user.alert-preferences'
import { Route as ApiDeviceIdStreamRouteImport } from './routes/api/device.$id.stream'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoute = RoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesRoute = ApiDevicesRouteImport.update({
  id: '/api/devices',
  path: '/api/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockAlertRoute = ApiMockAlertRouteImport.update({
  id: '/api/mock-alert',
  path: '/api/mock-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWeatherRoute = ApiWeatherRouteImport.update({
  id: '/api/weather',
  path: '/api/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHistoryRoute = DashboardHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecommendationsRoute =
  DashboardRecommendationsRouteImport.update({
    id: '/recommendations',
    path: '/recommendations',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardRoomsRoute = DashboardRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWeatherRoute = DashboardWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiDeviceDataRoute = ApiDeviceDataRouteImport.update({
  id: '/api/device/data',
  path: '/api/device/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeviceHistoryRoute = ApiDeviceHistoryRouteImport.update({
  id: '/api/device/history',
  path: '/api/device/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeviceLatestRoute = ApiDeviceLatestRouteImport.update({
  id: '/api/device/latest',
  path: '/api/device/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevicesIdRoute = ApiDevicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDevicesRoute,
} as any)
const ApiDevicesDataRoute = ApiDevicesDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => ApiDevicesRoute,
} as any)
const ApiPushSubscribeRoute = ApiPushSubscribeRouteImport.update({
  id: '/api/push/subscribe',
  path: '/api/push/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushVapidRoute = ApiPushVapidRouteImport.update({
  id: '/api/push/vapid',
  path: '/api/push/vapid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserAlertPreferencesRoute = ApiUserAlertPreferencesRouteImport.update({
  id: '/api/user/alert-preferences',
  path: '/api/user/alert-preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeviceIdStreamRoute = ApiDeviceIdStreamRouteImport.update({
  id: '/api/device/$id/stream',
  path: '/api/device/$id/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/history': typeof HistoryRoute
  '/recommendations': typeof RecommendationsRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/weather': typeof WeatherRoute
  '/api/devices': typeof ApiDevicesRouteWithChildren
  '/api/mock-alert': typeof ApiMockAlertRoute
  '/api/weather': typeof ApiWeatherRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/rooms': typeof DashboardRoomsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/device/data': typeof ApiDeviceDataRoute
  '/api/device/history': typeof ApiDeviceHistoryRoute
  '/api/device/latest': typeof ApiDeviceLatestRoute
  '/api/devices/$id': typeof ApiDevicesIdRoute
  '/api/devices/data': typeof ApiDevicesDataRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/vapid': typeof ApiPushVapidRoute
  '/api/user/alert-preferences': typeof ApiUserAlertPreferencesRoute
  '/api/device/$id/stream': typeof ApiDeviceIdStreamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/recommendations': typeof RecommendationsRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/weather': typeof WeatherRoute
  '/api/devices': typeof ApiDevicesRouteWithChildren
  '/api/mock-alert': typeof ApiMockAlertRoute
  '/api/weather': typeof ApiWeatherRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/rooms': typeof DashboardRoomsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/device/data': typeof ApiDeviceDataRoute
  '/api/device/history': typeof ApiDeviceHistoryRoute
  '/api/device/latest': typeof ApiDeviceLatestRoute
  '/api/devices/$id': typeof ApiDevicesIdRoute
  '/api/devices/data': typeof ApiDevicesDataRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/vapid': typeof ApiPushVapidRoute
  '/api/user/alert-preferences': typeof ApiUserAlertPreferencesRoute
  '/api/device/$id/stream': typeof ApiDeviceIdStreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/history': typeof HistoryRoute
  '/recommendations': typeof RecommendationsRoute
  '/rooms': typeof RoomsRoute
  '/settings': typeof SettingsRoute
  '/weather': typeof WeatherRoute
  '/api/devices': typeof ApiDevicesRouteWithChildren
  '/api/mock-alert': typeof ApiMockAlertRoute
  '/api/weather': typeof ApiWeatherRoute
  '/dashboard/history': typeof DashboardHistoryRoute
  '/dashboard/recommendations': typeof DashboardRecommendationsRoute
  '/dashboard/rooms': typeof DashboardRoomsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/weather': typeof DashboardWeatherRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/device/data': typeof ApiDeviceDataRoute
  '/api/device/history': typeof ApiDeviceHistoryRoute
  '/api/device/latest': typeof ApiDeviceLatestRoute
  '/api/devices/$id': typeof ApiDevicesIdRoute
  '/api/devices/data': typeof ApiDevicesDataRoute
  '/api/push/subscribe': typeof ApiPushSubscribeRoute
  '/api/push/vapid': typeof ApiPushVapidRoute
  '/api/user/alert-preferences': typeof ApiUserAlertPreferencesRoute
  '/api/device/$id/stream': typeof ApiDeviceIdStreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/recommendations'
    | '/rooms'
    | '/settings'
    | '/weather'
    | '/api/devices'
    | '/api/mock-alert'
    | '/api/weather'
    | '/dashboard/history'
    | '/dashboard/recommendations'
    | '/dashboard/rooms'
    | '/dashboard/settings'
    | '/dashboard/weather'
    | '/dashboard/'
    | '/api/device/data'
    | '/api/device/history'
    | '/api/device/latest'
    | '/api/devices/$id'
    | '/api/devices/data'
    | '/api/push/subscribe'
    | '/api/push/vapid'
    | '/api/user/alert-preferences'
    | '/api/device/$id/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/recommendations'
    | '/rooms'
    | '/settings'
    | '/weather'
    | '/api/devices'
    | '/api/mock-alert'
    | '/api/weather'
    | '/dashboard/history'
    | '/dashboard/recommendations'
    | '/dashboard/rooms'
    | '/dashboard/settings'
    | '/dashboard/weather'
    | '/dashboard'
    | '/api/device/data'
    | '/api/device/history'
    | '/api/device/latest'
    | '/api/devices/$id'
    | '/api/devices/data'
    | '/api/push/subscribe'
    | '/api/push/vapid'
    | '/api/user/alert-preferences'
    | '/api/device/$id/stream'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/recommendations'
    | '/rooms'
    | '/settings'
    | '/weather'
    | '/api/devices'
    | '/api/mock-alert'
    | '/api/weather'
    | '/dashboard/history'
    | '/dashboard/recommendations'
    | '/dashboard/rooms'
    | '/dashboard/settings'
    | '/dashboard/weather'
    | '/dashboard/'
    | '/api/device/data'
    | '/api/device/history'
    | '/api/device/latest'
    | '/api/devices/$id'
    | '/api/devices/data'
    | '/api/push/subscribe'
    | '/api/push/vapid'
    | '/api/user/alert-preferences'
    | '/api/device/$id/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RoomsRoute: typeof RoomsRoute
  SettingsRoute: typeof SettingsRoute
  WeatherRoute: typeof WeatherRoute
  ApiDevicesRoute: typeof ApiDevicesRouteWithChildren
  ApiMockAlertRoute: typeof ApiMockAlertRoute
  ApiWeatherRoute: typeof ApiWeatherRoute
  ApiDeviceDataRoute: typeof ApiDeviceDataRoute
  ApiDeviceHistoryRoute: typeof ApiDeviceHistoryRoute
  ApiDeviceLatestRoute: typeof ApiDeviceLatestRoute
  ApiPushSubscribeRoute: typeof ApiPushSubscribeRoute
  ApiPushVapidRoute: typeof ApiPushVapidRoute
  ApiUserAlertPreferencesRoute: typeof ApiUserAlertPreferencesRoute
  ApiDeviceIdStreamRoute: typeof ApiDeviceIdStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms': {
      id: '/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices': {
      id: '/api/devices'
      path: '/api/devices'
      fullPath: '/api/devices'
      preLoaderRoute: typeof ApiDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock-alert': {
      id: '/api/mock-alert'
      path: '/api/mock-alert'
      fullPath: '/api/mock-alert'
      preLoaderRoute: typeof ApiMockAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/weather': {
      id: '/api/weather'
      path: '/api/weather'
      fullPath: '/api/weather'
      preLoaderRoute: typeof ApiWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/history': {
      id: '/dashboard/history'
      path: '/history'
      fullPath: '/dashboard/history'
      preLoaderRoute: typeof DashboardHistoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recommendations': {
      id: '/dashboard/recommendations'
      path: '/recommendations'
      fullPath: '/dashboard/recommendations'
      preLoaderRoute: typeof DashboardRecommendationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rooms': {
      id: '/dashboard/rooms'
      path: '/rooms'
      fullPath: '/dashboard/rooms'
      preLoaderRoute: typeof DashboardRoomsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/weather': {
      id: '/dashboard/weather'
      path: '/weather'
      fullPath: '/dashboard/weather'
      preLoaderRoute: typeof DashboardWeatherRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/device/data': {
      id: '/api/device/data'
      path: '/api/device/data'
      fullPath: '/api/device/data'
      preLoaderRoute: typeof ApiDeviceDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device/history': {
      id: '/api/device/history'
      path: '/api/device/history'
      fullPath: '/api/device/history'
      preLoaderRoute: typeof ApiDeviceHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device/latest': {
      id: '/api/device/latest'
      path: '/api/device/latest'
      fullPath: '/api/device/latest'
      preLoaderRoute: typeof ApiDeviceLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/devices/$id': {
      id: '/api/devices/$id'
      path: '/$id'
      fullPath: '/api/devices/$id'
      preLoaderRoute: typeof ApiDevicesIdRouteImport
      parentRoute: typeof ApiDevicesRoute
    }
    '/api/devices/data': {
      id: '/api/devices/data'
      path: '/data'
      fullPath: '/api/devices/data'
      preLoaderRoute: typeof ApiDevicesDataRouteImport
      parentRoute: typeof ApiDevicesRoute
    }
    '/api/push/subscribe': {
      id: '/api/push/subscribe'
      path: '/api/push/subscribe'
      fullPath: '/api/push/subscribe'
      preLoaderRoute: typeof ApiPushSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push/vapid': {
      id: '/api/push/vapid'
      path: '/api/push/vapid'
      fullPath: '/api/push/vapid'
      preLoaderRoute: typeof ApiPushVapidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/alert-preferences': {
      id: '/api/user/alert-preferences'
      path: '/api/user/alert-preferences'
      fullPath: '/api/user/alert-preferences'
      preLoaderRoute: typeof ApiUserAlertPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/device/$id/stream': {
      id: '/api/device/$id/stream'
      path: '/api/device/$id/stream'
      fullPath: '/api/device/$id/stream'
      preLoaderRoute: typeof ApiDeviceIdStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardHistoryRoute: typeof DashboardHistoryRoute
  DashboardRecommendationsRoute: typeof DashboardRecommendationsRoute
  DashboardRoomsRoute: typeof DashboardRoomsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardWeatherRoute: typeof DashboardWeatherRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardHistoryRoute: DashboardHistoryRoute,
  DashboardRecommendationsRoute: DashboardRecommendationsRoute,
  DashboardRoomsRoute: DashboardRoomsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardWeatherRoute: DashboardWeatherRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiDevicesRouteChildren {
  ApiDevicesIdRoute: typeof ApiDevicesIdRoute
  ApiDevicesDataRoute: typeof ApiDevicesDataRoute
}

const ApiDevicesRouteChildren: ApiDevicesRouteChildren = {
  ApiDevicesIdRoute: ApiDevicesIdRoute,
  ApiDevicesDataRoute: ApiDevicesDataRoute,
}

const ApiDevicesRouteWithChildren = ApiDevicesRoute._addFileChildren(
  ApiDevicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  HistoryRoute: HistoryRoute,
  RecommendationsRoute: RecommendationsRoute,
  RoomsRoute: RoomsRoute,
  SettingsRoute: SettingsRoute,
  WeatherRoute: WeatherRoute,
  ApiDevicesRoute: ApiDevicesRouteWithChildren,
  ApiMockAlertRoute: ApiMockAlertRoute,
  ApiWeatherRoute: ApiWeatherRoute,
  ApiDeviceDataRoute: ApiDeviceDataRoute,
  ApiDeviceHistoryRoute: ApiDeviceHistoryRoute,
  ApiDeviceLatestRoute: ApiDeviceLatestRoute,
  ApiPushSubscribeRoute: ApiPushSubscribeRoute,
  ApiPushVapidRoute: ApiPushVapidRoute,
  ApiUserAlertPreferencesRoute: ApiUserAlertPreferencesRoute,
  ApiDeviceIdStreamRoute: ApiDeviceIdStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
